# Generated by Django 5.2.6 on 2025-11-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
